services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8000"
    networks:
      - devnetwork

networks:
  devnetwork:
    external: true