import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { AuthProvider } from "@/components/AuthProvider"
import { GoogleOAuthProvider } from '@react-oauth/google'



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <GoogleOAuthProvider clientId="454329887491-3vjn6t36k4c45l2l3n96k87gl77v5jjq.apps.googleusercontent.com">

        {children}
        </GoogleOAuthProvider>
        </AuthProvider>
        
      </body>
    </html>
  );
}
